### ISSUE TITLE
UID < 1000 for system user

### ISSUE THREAD

**Issue by DaaNMaGeDDoN** [Bercik1337/rt-auto-install#30]
I just created a system account (Debian bullseye "useradd -r") before i found your script, however it expects a UID > 1000, which doesn't make sense because you refer to the account as a system account.

I heave not checked why this is a requirement, might be for setting it up the way you did maybe, but i just happen to have read this https://askubuntu.com/questions/523949/what-is-a-system-group-as-opposed-to-a-normal-group , see answer #1.

So in terms of security the number of the ID doesn't mean anything, however historically speaking system accounts' UID are <1000. 

I guess the check is not checking what it should or can just go away?

**Comment by Bercik1337** [comment]
@DaaNMaGeDDoN this check was present in the original script (before i took it over).

After giving it some thought, I'd rather stay with "normal" user UID. 
It's not like service account is "more powerful" or something, but benefit of having current check is: when newbie will create user account user wizard or something, it will work.  Additionally having "users" group could provide read access for files to other users on the same system.
BUT MOST IMPORTANTLY
This is used by people who usually don't know what they are doing - as a result **it's very often they use their own account for rt instead of creating a separate one.**

What you propose is not wrong. Is just not beneficial (especially for noobs). So I think i'm going leave it as it is. After all - to modify behavior is a simple edit in one function, and there you go. Or you can clone repo and edit your own copy. But is it all that worth?

UNLESS there's something else I'm not seeing and you can point it out. Then I'll reconsider again.

**Comment by DaaNMaGeDDoN** [comment]
And their own account is probably just ID 1000, often the first user account created. So, yeah it will prevent them from probably using their own account, however since i wanted to actually use a (prepared) system account (UID<1000), i couldn't.  Maybe just check if the ID is not equal to 1000 (or 0 of course) and don't call it a system account, just "an account"? 
Anyway i forgot to thank you for the script, sorry about that, it worked like a charm apart from this uid thingy, cheers!

**Comment by Bercik1337** [comment]
@DaaNMaGeDDoN  function SET_RTORRENT_USER does that. It checks if it's root (not allowed), it check if it even exist (must be valid account), and 
`elif [[ $(cat /etc/passwd | grep "^$RTORRENT_USER:" | cut -d: -f3) -lt 999 ]]; then`

This ALLOWS user with uid 1000 to be used :)

So if my understanding is correct you could pretty much change 999 to 1 and your problem is solved. I'll try to test it when I got few min spare time (no soon)

Sorry for late replies but I'm super busy :(

**Comment by Bercik1337** [comment]
Just implemented the change. I hope you will enjoy :)

**Comment by DaaNMaGeDDoN** [comment]
Cheers, sorry i was busy too, if i wasn't i would gladly have tested your change, thanks again (hope i don't re-open this with commenting). I really need to get more xp using github, i bet i could have helped you by offering some kind of patch, bit lazy from my end, kudos to you!
