### ISSUE TITLE
Package 'libapache2-mod-scgi' has no installation candidate

### ISSUE THREAD

**Issue by mjd119** [Bercik1337/rt-auto-install#7]
The script description says it is compatible with Debian 11 Bullseye, but it appears that the package "libapache2-mod-scgi" is only available in the sid and buster repositories. A note should be made about repositories to enable to ensure compatibility if this package has no equivalent in Debian 11 bullseye and can only be found in the sid or buster repositories. The script does not let me continue currently.
EDIT:
After enabling the unstable debian repository, I still get the same error message which seems to come from issues with [line 318](https://github.com/Bercik1337/rt-auto-install/blob/master/Rt-Install-minimal#L318). The package "libapache2-mod-scgi" is only available in [debports](https://packages.debian.org/sid/httpd/libapache2-mod-scgi) for experimental. Has compatibility with Debian 11 Bullseye been confirmed through installation on a local machine?

**Comment by Bercik1337** [comment]
Thanks for noticing. You are correct it is not working anymore. Just tested in VM.
> Has compatibility with Debian 11 Bullseye been confirmed through installation on a local machine?
Yes it was, I tested it shortly before last commit. 

They must've remove the package (temporarily or not). Fun fact - this same package is also gone in Ubuntu 20.04. I don't know if it's on purpose or not. I'm not a programmer so I'm unaware if this is a trend to remove it, or maybe there is a new generation/substitute for it?
Do you know anything about it maybe? 
Bullseye is under development so anything can change here - but Ubu20.04 is not, so I'm afraid this package missing is a thing.

Any idea for workaround? (other than  moving to nginx, because I see it has the support for SCGI).?

In the meantime I'll remove Debian 11 from supported OS list not to confuse people.

**Comment by Pingblue** [comment]
I just noticed this in Ubuntu 20.04 you can install in Ubuntu/Debian through the deb.

wget http://mirrors.kernel.org/ubuntu/pool/universe/s/scgi/libapache2-mod-scgi_1.13-1.1build1_amd64.deb
dpkg -i libapache2-mod-scgi_1.13-1.1build1_amd64.deb

**Comment by Bercik1337** [comment]
@Pingblue hey thanks for finding this out, last time I checked it wasn't in repo, but manual installation of deb pkg will also help (well as a workaround). I'll take a look at it after weekend.

**Comment by Bercik1337** [comment]
@Pingblue hey buddy. I just commited v0.8 with manual installation of .deb for scgi package. It works fine on my Ubuntu 20.04.1 VM. Lemme know if it works for you too.
If I have the time I'll look for deb packages for Debian 11 as well, this could (finally) bring back this functionality.
